#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/vcluster
#
# IDENTIFICATION
#    src/backend/storage/vcluster/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/vcluster
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS =  vcluster.o vcache.o vcache_hash.o vchain.o vchain_hash.o thread_table.o dead_zone.o vstatistic.o cstatistic.o

include $(top_srcdir)/src/backend/common.mk
